### PR TITLE
Support arrays of per file ignore options

### LINKED ISSUE #160: [BUG] doesn't support TOML list in `per-file-ignores`
This `pyproject.toml` will blow up with `pylint==3.2.6` and `pylint-per-file-ignores==1.3.2`:

```toml
[tool.pylint.messages_control]
per-file-ignores = [
    "scripts/modal/:import-error",  # Modal Image imports are a false positive
    "scripts/db.py:not-callable",  # not-callable is a false positive, SEE: https://github.com/pylint-dev/pylint/issues/8138
]
```

It blows up with an error on splitting in https://github.com/christopherpickering/pylint-per-file-ignores/blob/v1.3.2/pylint_per_file_ignores/__init__.py#L252-L257:

```none
Traceback (most recent call last):
  File "/path/to/venv/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
             ^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.12/site-packages/pylint/__init__.py", line 34, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/path/to/venv/lib/python3.12/site-packages/pylint/lint/run.py", line 162, in __init__
    args = _config_initialization(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.12/site-packages/pylint/config/config_initialization.py", line 135, in _config_initialization
    linter.load_plugin_configuration()
  File "/path/to/venv/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 407, in load_plugin_configuration
    module_or_error.load_configuration(self)
  File "/path/to/venv/lib/python3.12/site-packages/pylint_per_file_ignores/__init__.py", line 253, in load_configuration
    linter.config.per_file_ignores = dict(
                                     ^^^^^
ValueError: dictionary update sequence element #0 has length 3; 2 is required
```

---

A workaround for not supporting TOML lists is string-ifying the `per-file-ignores` with DIY `\n`:

```toml
[tool.pylint.messages_control]
# Modal Image imports are a false positive
# not-callable is a false positive, SEE: https://github.com/pylint-dev/pylint/issues/8138
per-file-ignores = "scripts/modal/:import-error,\nscripts/db.py:not-callable"
```

### PR DESCRIPTION
**Pull request by JamesParrott**
I'm not sure how to test this, and hence am not sure if this works, but perhaps this fixes #160?

### CODE REVIEW

**Comment by christopherpickering** [comment]
Thanks! Do you mind to make the lint pass? I made the tests run.

**Comment by JamesParrott** [comment]
You're welcome.  I don't mind at all - given the nature of this project, running a linter should've occured to me sooner.

**Comment by JamesParrott** [comment]
Hi Christophe. These latest failures are from lots of different lines being too long, perhaps due to the Black line length setting whose name I changed re-enabled.  I've added the same setting to Ruff, and linting seems to pass now on my fork:

https://github.com/JamesParrott/pylint-per-file-ignores/actions/runs/12027829692

**Comment by christopherpickering** [comment]
Thanks! sorry for the delay here.

**Comment by JamesParrott** [comment]
No problem.  Thanks Christopher :).

**Comment by adamtheturtle** [comment]
@christopherpickering Please could we get a release with this change?

**Comment by adamtheturtle** [comment]
Thank you @christopherpickering !

**Comment by JamesParrott** [comment]
Great stuff Christopher

**Comment by christopherpickering** [comment]
Thanks for using it 😁

**Pull request merged**
